## Numpy

In [34]:
import numpy as np

In [56]:
# Creating arrays
mylist=[1,2,3]
x=np.array(mylist)
x

array([1, 2, 3])

In [36]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [37]:
m = np.array([[7,8,9],
             [10,11,12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [38]:
m.shape

(2, 3)

In [39]:
a = np.arange(36)

In [40]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [41]:
a.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [42]:
a=a.reshape(6,6)

In [43]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [44]:
a.shape

(6, 6)

In [45]:
a.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [46]:
a[[2,3],[2,3]]

array([14, 21])

In [47]:
a[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [48]:
z = np.linspace(0,5,8)
z

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [21]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [28]:
np.array([1,2,3] * 2)

array([1, 2, 3, 1, 2, 3])

In [29]:
np.repeat([1,2,3],3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [30]:
# Combining arrays
p = np.ones((2,3),int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
np.vstack([p,2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [32]:
np.hstack([p,3*p])

array([[1, 1, 1, 3, 3, 3],
       [1, 1, 1, 3, 3, 3]])

## Operations

In [49]:
x+y

array([5, 7, 9])

In [50]:
x * y

array([ 4, 10, 18])

In [51]:
x ** 2

array([1, 4, 9])

In [52]:
x.dot(y)

32

In [54]:
b = np.array([y,y**2])
b

array([[ 4,  5,  6],
       [16, 25, 36]])

In [58]:
b.shape

(2, 3)

In [59]:
# Transpose
b.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [60]:
b.T.shape

(3, 2)

In [61]:
b.dtype

dtype('int64')

In [62]:
b = b.astype('f')
b.dtype

dtype('float32')

In [63]:
c = np.array([2,4,3,-7,-2,8])

In [64]:
# Sum
c.sum()

8

In [66]:
print(c.max()) # Max
print(c.min()) # Min 
print(c.mean()) # Mean
print(c.std()) # Standard Deviation

8
-7
1.3333333333333333
4.74926894959167


In [67]:
c.argmax() # index of max

5

In [68]:
c.argmin() # index of min

3